apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fatimarathore2018/backend_hms:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://database-service:27017/OasisHospitalManagementSystem
            - name: STREAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-stream-secrets
                  key: STREAM_API_KEY
            - name: STREAM_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-stream-secrets
                  key: STREAM_API_SECRET
            - name: STRIPE_PUBLISH_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-stream-secrets
                  key: STRIPE_PUBLISH_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-stream-secrets
                  key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
