name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        $minikubeEnv = & minikube docker-env --shell powershell
        $minikubeEnv | ForEach-Object { Invoke-Expression $_ }
      shell: pwsh

    - name: Build Backend Docker image
      run: |
        docker build -t fatimarathore2018/backend_hms:latest -f backend/Dockerfile .
      shell: pwsh

    - name: Build Frontend Docker image
      run: |
        docker build -t fatimarathore2018/frontend_hospital_management_system:latest -f frontend/Dockerfile .
      shell: pwsh

    - name: Login to Docker Hub
      run: |
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      shell: pwsh

    - name: Push Backend Docker image to Docker Hub
      run: docker push fatimarathore2018/backend_hms:latest
      shell: pwsh

    - name: Push Frontend Docker image to Docker Hub
      run: docker push fatimarathore2018/frontend_hospital_management_system:latest
      shell: pwsh

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/backend_deployment_hospital_management_system.yaml 
        kubectl apply -f kubernetes/frontend_deployment_hospital_management_system.yaml
        kubectl apply -f kubernetes/database_deployment_hospital_management_system.yaml
      shell: pwsh
